version: '3.7'

services:
  nodejs-demo-web:
    build: 
      context: ./nodejs-demo
      dockerfile: Dockerfile
    networks:
      - demo-kubernetes

  csharp-demo-web:
    build: 
      context: ./csharp-demo
      dockerfile: Dockerfile
    networks:
      - demo-kubernetes

networks:
  demo-kubernetes: