apiVersion: v1
kind: Pod
metadata:
  name: nodejs-demo
  labels:
    name: helloworld
spec:
  containers:
  - name: k8s-nodejs-demo
    image: theanaoliveira/nodejs-demo:1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
