apiVersion: v1
kind: Service
metadata:
  name: service-nodejs-demo
spec:
  selector:
    app: helloworld
  ports:
  - port: 31117
    nodePort: 31117
    targetPort: nodejs-port
    protocol: TCP
  type: NodePort